# The URL the site will be built for
base_url = "https://cameron.rs"

title="cameron - software engineer"

description = "My main portfolio where you can learn about me"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "charcoal"
render_emoji = true

[extra]
github="https://github.com/wzid"
linkedin="https://www.linkedin.com/in/cameron-k-a00565257"
email="me@cameron.rs"
# Put all your custom variables here
menu_links = [
    { url = "https://blog.cameron.rs", name = "Blog", icon = "fa-solid fa-newspaper" },
    { url = "https://projects.cameron.rs", name = "Projects", icon="fa-solid fa-book-bookmark" },
    { url = "https://docs.cameron.rs", name = "Documentation" },
]
projects = [
    { name = "sudoku-solver", description = "Sudoku puzzle solver using bit manipulation and bitmasks with Rust 🦀 and egui 🎨", url = "https://github.com/wzid/sudoku-solver", lang = "Rust", color = "#DFA584" },
    { name = "stats-on-discord", description = "Minecraft plugin that continually updates embeds to show real time server statistics of players", url = "https://github.com/wzid/stats-on-discord", lang = "Java", color = "#B07219" },
    { name = "vscode-to-vs", description = "Command to create the solution files needed for a Visual Studio C++ project with just source files ", url = "https://github.com/wzid/vscode-to-vs", lang = "Rust", color = "#DFA584" },
]